apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: {{ .Values.server }}
  project: kube-prometheus
  source:
    path: helm_charts/kube-state-metrics
    repoURL: https://github.com/TechTalkFridays/eks-kube-prometheus.git
    targetRevision: production
    helm:
      valueFiles:
      - helm_vars/production/values.yaml
 syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
