apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: grafana
{{- if .Values.ingress.nginx.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-grafana
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.externalUrl }}
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 80
{{- end }}
