---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: grafana-config
  namespace: {{ .Release.Namespace }}
secretDescriptor:
  backendType: secretsManager
  data:
    - key: {{ .Values.secretName }}
      name: grafana.ini
      property: grafana.ini
