apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.33.0
  name: prometheus-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/version: v0.33.0
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --config-reloader-image={{ .Values.prometheusOperator.configmapReloaderImage }}
        - --prometheus-config-reloader={{ .Values.prometheusOperator.configReloaderImage }}
        image: {{ .Values.prometheusOperator.image }}
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
{{- if hasKey .Values.prometheusOperator "resources" }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
        securityContext:
          allowPrivilegeEscalation: false
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
