---
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: prometheus-k8s
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: web
    port: 80
    targetPort: 9090
  selector:
    app: prometheus
    prometheus: k8s
  sessionAffinity: ClientIP
{{- if .Values.prometheus.ingress.nginx.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-prometheus
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
{{- if .Values.prometheus.ingress.nginx.http_x_forwarded_proto }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_x_forwarded_proto != 'https') {
        return 301 https://$host$request_uri;
      }
{{- end }}
spec:
  rules:
  - host: {{ .Values.prometheus.externalUrl }}
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-k8s
          servicePort: 80
{{- end }}
