---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: alertmanager-main
  namespace: {{ .Release.Namespace }}
secretDescriptor:
  backendType: secretsManager
  data:
    - key: {{ .Values.secretName }}
      name: alertmanager.yaml
      property: alertmanager.yaml
