prometheus:
  baseImage: 'quay.io/prometheus/prometheus'
  version: 'v2.11.0'
  replicas: 2
  externalUrl: 'prom.engineering.com'
  secretName: /engineering/monitoring/prometheus-additional-scrape
  kubeletPort: https
  ingress:
    nginx:
      enabled: true
      http_x_forwarded_proto: true
    istio:
      enabled: false
  data:
    class: 'gp2'
    storage: 300Gi
    rotation: '60d'
  resources:
    limits:
      cpu: 0.3
      memory: 4Gi
    requests:
      cpu: 0.2
      memory: 2Gi

prometheusAdapater:
  image: 'quay.io/coreos/k8s-prometheus-adapter-amd64:v0.5.0'
  resources: {}

prometheusOperator:
  image: 'quay.io/coreos/prometheus-operator:v0.33.0'
  configmapReloaderImage: 'quay.io/coreos/configmap-reload:v0.0.1'
  configReloaderImage: 'quay.io/coreos/prometheus-config-reloader:v0.33.0'
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
