apiVersion: v1
name: engineering-kube-prometheus
version: 0.0.1
appVersion: 0.0.1
description: Helm chart for kube-prometheus
keywords:
  - kube-prometheus
sources:
  - git@github.com:TechTalkFridays/eks-kube-prometheus.git
engine: gotpl
